<<<<<<< HEAD
name = "firefly"
compatibility_date = "2026-05-05"

[assets]
directory = "./dist"

[vars]
=======
name = "firefly"
compatibility_date = "2026-05-05"

[assets]
directory = "./dist"

[vars]
>>>>>>> 07e78b32209159dd00eb301b96546a908abcfab3
NODE_VERSION = "22"